In [11]:
import pandas as pd
import numpy as np

1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

In [36]:
exercicio = np.random.randint(0, 100, size=(2, 5))

print(exercicio)
print(exercicio.dtype)

[[68 76 39  6 42]
 [13 74 49  9 46]]
int32


2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [39]:
matriz = np.random.rand(5, 5)

min = np.min(matriz)
max = np.max(matriz)
mean = np.average(matriz)

print("Mínimo:", min)
print("Máximo:", max)
print("Média:", mean)

Mínimo: 0.006302553228888175
Máximo: 0.9682727294617259
Média: 0.5752721812408796


3. Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.


In [33]:
array1 = np.random.rand(10)

array_final = (array1 * 10).astype(int)

# Imprime os arrays
print("Primeiro Array:")
print(array1)
print("\nArray Final:")
print(array_final)


Primeiro Array:
[0.9978793  0.65050169 0.04555515 0.83226339 0.93301226 0.25421486
 0.38351584 0.28458017 0.00247561 0.72852367]

Array Final:
[9 6 0 8 9 2 3 2 0 7]


4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [40]:
mat = np.random.randint(0, 10, (3, 3))

mat[1, :] = -1

print(mat)

[[ 7  0  1]
 [-1 -1 -1]
 [ 0  6  9]]


5. Crie um DataFrame com as seguintes informações:
Coluna "fruta": "Banana", "Maça", "Pera"
Coluna "preco": 7.90, 10.20, 11.80
Coluna "quantidade": 12, 3, 4

In [34]:
df1 = {
    'fruta': ['Banana', 'Maça', 'Pera'],
    'preco': [7.90, 10.20, 11.80],
    'quantidade': [12, 3, 4] }

df = pd.DataFrame (df1)
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4